-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 22:44:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TAIBank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TAIBank` ;

-- -----------------------------------------------------
-- Schema TAIBank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TAIBank` DEFAULT CHARACTER SET utf8 ;
USE `TAIBank` ;

-- -----------------------------------------------------
-- Table `TAIBank`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAIBank`.`users` ;

CREATE TABLE IF NOT EXISTS `TAIBank`.`users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` INT NULL,
  `PIN` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAIBank`.`debit_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAIBank`.`debit_card` ;

CREATE TABLE IF NOT EXISTS `TAIBank`.`debit_card` (
  `id_debit_card` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT UNSIGNED NOT NULL,
  `balance` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_debit_card`),
  UNIQUE INDEX `id_debit_card_UNIQUE` (`id_debit_card` ASC),
  INDEX `user_debit_idx` (`id_user` ASC),
  CONSTRAINT `user_debit`
    FOREIGN KEY (`id_user`)
    REFERENCES `TAIBank`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TAIBank`.`debit_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TAIBank`.`debit_transaction` ;

CREATE TABLE IF NOT EXISTS `TAIBank`.`debit_transaction` (
  `debit_transaction_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_card` INT UNSIGNED NULL,
  `to_card` INT UNSIGNED NULL,
  `amount` BIGINT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `comment` VARCHAR(45) NULL,
  `type`INT UNSIGNED NOT NULL,
  PRIMARY KEY (`debit_transaction_id`),
  INDEX `from_card_id_idx` (`from_card` ASC),
  INDEX `to_card_id_idx` (`to_card` ASC),
  UNIQUE INDEX `debit_transaction_id_UNIQUE` (`debit_transaction_id` ASC),
  CONSTRAINT `from_card_id`
    FOREIGN KEY (`from_card`)
    REFERENCES `TAIBank`.`debit_card` (`id_debit_card`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `to_card_id`
    FOREIGN KEY (`to_card`)
    REFERENCES `TAIBank`.`debit_card` (`id_debit_card`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
